[2024-10-13T02:12:28.291-0400] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-13T02:12:28.305-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bixi_etl_pipeline.extract_task manual__2024-10-13T06:12:15.007882+00:00 [queued]>
[2024-10-13T02:12:28.314-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bixi_etl_pipeline.extract_task manual__2024-10-13T06:12:15.007882+00:00 [queued]>
[2024-10-13T02:12:28.315-0400] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-13T02:12:28.330-0400] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_task> on 2024-10-13 06:12:15.007882+00:00
[2024-10-13T02:12:28.338-0400] {standard_task_runner.py:72} INFO - Started process 4309 to run task
[2024-10-13T02:12:28.344-0400] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-13T02:12:28.356-0400] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'bixi_etl_pipeline', 'extract_task', 'manual__2024-10-13T06:12:15.007882+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/bixi_etl_pipeline.py', '--cfg-path', '/var/folders/bj/4z3t139j7xj2qng4wk4y16ym0000gn/T/tmpc0x8yt35']
[2024-10-13T02:12:28.357-0400] {standard_task_runner.py:105} INFO - Job 144: Subtask extract_task
[2024-10-13T02:12:28.417-0400] {task_command.py:467} INFO - Running <TaskInstance: bixi_etl_pipeline.extract_task manual__2024-10-13T06:12:15.007882+00:00 [running]> on host karendembp.home
[2024-10-13T02:12:28.497-0400] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
BrokenPipeError: [Errno 32] Broken pipe
[2024-10-13T02:12:28.499-0400] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-13T02:12:28.499-0400] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2024-10-13T02:12:28.502-0400] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-13T02:12:28.506-0400] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bixi_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T06:12:15.007882+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-13T06:12:15.007882+00:00'
[2024-10-13T02:12:28.509-0400] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-13T02:12:28.510-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-13T02:12:28.511-0400] {logging_mixin.py:190} INFO - Current task name:extract_task state:running start_date:2024-10-13 06:12:28.305679+00:00
[2024-10-13T02:12:28.512-0400] {logging_mixin.py:190} INFO - Dag name:bixi_etl_pipeline and current dag run status:running
[2024-10-13T02:12:28.513-0400] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-13T02:12:29.169-0400] {python.py:240} INFO - Done. Returned value was: None
[2024-10-13T02:12:29.175-0400] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-13T02:12:29.177-0400] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=bixi_etl_pipeline, task_id=extract_task, run_id=manual__2024-10-13T06:12:15.007882+00:00, execution_date=20241013T061215, start_date=20241013T061228, end_date=20241013T061229
[2024-10-13T02:12:29.187-0400] {logging_mixin.py:190} INFO - Task instance in success state
[2024-10-13T02:12:29.189-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-10-13T02:12:29.190-0400] {logging_mixin.py:190} INFO - Dag name:bixi_etl_pipeline queued_at:2024-10-13 06:12:15.043631+00:00
[2024-10-13T02:12:29.191-0400] {logging_mixin.py:190} INFO - Task hostname:karendembp.home operator:PythonOperator
[2024-10-13T02:12:29.226-0400] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-13T02:12:29.261-0400] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-13T02:12:29.263-0400] {local_task_job_runner.py:245} INFO - ::endgroup::
