[2024-10-13T17:10:16.653-0400] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-13T17:10:16.670-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bixi_etl_pipeline.transform_task manual__2024-10-13T21:09:38.519028+00:00 [queued]>
[2024-10-13T17:10:16.679-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bixi_etl_pipeline.transform_task manual__2024-10-13T21:09:38.519028+00:00 [queued]>
[2024-10-13T17:10:16.680-0400] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-13T17:10:16.700-0400] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): transform_task> on 2024-10-13 21:09:38.519028+00:00
[2024-10-13T17:10:16.709-0400] {standard_task_runner.py:72} INFO - Started process 70867 to run task
[2024-10-13T17:10:16.716-0400] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-13T17:10:16.728-0400] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'bixi_etl_pipeline', 'transform_task', 'manual__2024-10-13T21:09:38.519028+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/bixi_etl_pipeline.py', '--cfg-path', '/var/folders/bj/4z3t139j7xj2qng4wk4y16ym0000gn/T/tmpoy80x8ql']
[2024-10-13T17:10:16.730-0400] {standard_task_runner.py:105} INFO - Job 179: Subtask transform_task
[2024-10-13T17:10:16.809-0400] {task_command.py:467} INFO - Running <TaskInstance: bixi_etl_pipeline.transform_task manual__2024-10-13T21:09:38.519028+00:00 [running]> on host karendembp.home
[2024-10-13T17:10:17.132-0400] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bixi_etl_pipeline' AIRFLOW_CTX_TASK_ID='transform_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T21:09:38.519028+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-13T21:09:38.519028+00:00'
[2024-10-13T17:10:17.134-0400] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-13T17:10:17.135-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-13T17:10:17.136-0400] {logging_mixin.py:190} INFO - Current task name:transform_task state:running start_date:2024-10-13 21:10:16.670671+00:00
[2024-10-13T17:10:17.137-0400] {logging_mixin.py:190} INFO - Dag name:bixi_etl_pipeline and current dag run status:running
[2024-10-13T17:10:17.137-0400] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-13T17:10:22.307-0400] {logging_mixin.py:190} INFO - Station Info Columns: ['capacity', 'eightd_has_key_dispenser', 'electric_bike_surcharge_waiver', 'external_id', 'has_kiosk', 'is_charging', 'lat', 'lon', 'name', 'rental_methods', 'short_name', 'station_id', 'eightd_station_services']
[2024-10-13T17:10:22.308-0400] {logging_mixin.py:190} INFO - Station Status Columns: ['eightd_has_available_keys', 'is_charging', 'is_installed', 'is_renting', 'is_returning', 'last_reported', 'num_bikes_available', 'num_bikes_disabled', 'num_docks_available', 'num_docks_disabled', 'num_ebikes_available', 'station_id', 'eightd_active_station_services']
[2024-10-13T17:10:22.716-0400] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/karenwang/airflow/dags/bixi_etl_pipeline.py", line 85, in transform_data
    from_unixtime(col('status_last_reported') / 1000, 'yyyy-MM-dd HH:mm:ss').alias('last_reported')
NameError: name 'from_unixtime' is not defined
[2024-10-13T17:10:22.725-0400] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-13T17:10:22.726-0400] {logging_mixin.py:190} INFO - Task start:2024-10-13 21:10:16.670671+00:00 end:2024-10-13 21:10:22.724639+00:00 duration:6.053968
[2024-10-13T17:10:22.727-0400] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform_task> dag:<DAG: bixi_etl_pipeline> dagrun:<DagRun bixi_etl_pipeline @ 2024-10-13 21:09:38.519028+00:00: manual__2024-10-13T21:09:38.519028+00:00, state:running, queued_at: 2024-10-13 21:09:38.550079+00:00. externally triggered: True>
[2024-10-13T17:10:22.728-0400] {logging_mixin.py:190} INFO - Failure caused by name 'from_unixtime' is not defined
[2024-10-13T17:10:22.729-0400] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=bixi_etl_pipeline, task_id=transform_task, run_id=manual__2024-10-13T21:09:38.519028+00:00, execution_date=20241013T210938, start_date=20241013T211016, end_date=20241013T211022
[2024-10-13T17:10:22.742-0400] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-13T17:10:22.744-0400] {standard_task_runner.py:124} ERROR - Failed to execute job 179 for task transform_task (name 'from_unixtime' is not defined; 70867)
Traceback (most recent call last):
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/karenwang/airflow/dags/bixi_etl_pipeline.py", line 85, in transform_data
    from_unixtime(col('status_last_reported') / 1000, 'yyyy-MM-dd HH:mm:ss').alias('last_reported')
NameError: name 'from_unixtime' is not defined
[2024-10-13T17:10:22.802-0400] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-13T17:10:22.827-0400] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-13T17:10:22.831-0400] {local_task_job_runner.py:245} INFO - ::endgroup::
