[2024-10-13T18:13:33.453-0400] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-13T18:13:33.469-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bixi_etl_pipeline.load_task manual__2024-10-13T22:12:20.313507+00:00 [queued]>
[2024-10-13T18:13:33.479-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bixi_etl_pipeline.load_task manual__2024-10-13T22:12:20.313507+00:00 [queued]>
[2024-10-13T18:13:33.479-0400] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-13T18:13:33.496-0400] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_task> on 2024-10-13 22:12:20.313507+00:00
[2024-10-13T18:13:33.505-0400] {standard_task_runner.py:72} INFO - Started process 90923 to run task
[2024-10-13T18:13:33.511-0400] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-13T18:13:33.523-0400] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'bixi_etl_pipeline', 'load_task', 'manual__2024-10-13T22:12:20.313507+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/bixi_etl_pipeline.py', '--cfg-path', '/var/folders/bj/4z3t139j7xj2qng4wk4y16ym0000gn/T/tmpxbx150hg']
[2024-10-13T18:13:33.524-0400] {standard_task_runner.py:105} INFO - Job 204: Subtask load_task
[2024-10-13T18:13:33.595-0400] {task_command.py:467} INFO - Running <TaskInstance: bixi_etl_pipeline.load_task manual__2024-10-13T22:12:20.313507+00:00 [running]> on host karendembp.home
[2024-10-13T18:13:33.886-0400] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bixi_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T22:12:20.313507+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-13T22:12:20.313507+00:00'
[2024-10-13T18:13:33.887-0400] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-13T18:13:33.888-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-13T18:13:33.889-0400] {logging_mixin.py:190} INFO - Current task name:load_task state:running start_date:2024-10-13 22:13:33.470205+00:00
[2024-10-13T18:13:33.890-0400] {logging_mixin.py:190} INFO - Dag name:bixi_etl_pipeline and current dag run status:running
[2024-10-13T18:13:33.891-0400] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-13T18:13:45.703-0400] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/karenwang/airflow/dags/bixi_etl_pipeline.py", line 123, in load_data_to_delta
    delta_table.alias("existing") \
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/delta/tables.py", line 1036, in execute
    self._jbuilder.execute()
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: Cannot resolve is_installed in UPDATE clause given columns new.station_id, new.capacity, new.eightd_has_key_dispenser, new.electric_bike_surcharge_waiver, new.external_id, new.has_kiosk, new.is_charging, new.lat, new.lon, new.name, new.rental_methods, new.short_name, new.eightd_station_services, new.eightd_has_available_keys, new.status_is_charging, new.status_is_installed, new.status_is_renting, new.status_is_returning, new.status_last_reported, new.status_num_bikes_available, new.num_bikes_disabled, new.num_docks_available, new.num_docks_disabled, new.num_ebikes_available, new.eightd_active_station_services, new.last_reported
[2024-10-13T18:13:45.724-0400] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-13T18:13:45.725-0400] {logging_mixin.py:190} INFO - Task start:2024-10-13 22:13:33.470205+00:00 end:2024-10-13 22:13:45.724122+00:00 duration:12.253917
[2024-10-13T18:13:45.726-0400] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_task> dag:<DAG: bixi_etl_pipeline> dagrun:<DagRun bixi_etl_pipeline @ 2024-10-13 22:12:20.313507+00:00: manual__2024-10-13T22:12:20.313507+00:00, state:running, queued_at: 2024-10-13 22:12:20.353824+00:00. externally triggered: True>
[2024-10-13T18:13:45.734-0400] {logging_mixin.py:190} INFO - Failure caused by Cannot resolve is_installed in UPDATE clause given columns new.station_id, new.capacity, new.eightd_has_key_dispenser, new.electric_bike_surcharge_waiver, new.external_id, new.has_kiosk, new.is_charging, new.lat, new.lon, new.name, new.rental_methods, new.short_name, new.eightd_station_services, new.eightd_has_available_keys, new.status_is_charging, new.status_is_installed, new.status_is_renting, new.status_is_returning, new.status_last_reported, new.status_num_bikes_available, new.num_bikes_disabled, new.num_docks_available, new.num_docks_disabled, new.num_ebikes_available, new.eightd_active_station_services, new.last_reported
[2024-10-13T18:13:45.736-0400] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=bixi_etl_pipeline, task_id=load_task, run_id=manual__2024-10-13T22:12:20.313507+00:00, execution_date=20241013T221220, start_date=20241013T221333, end_date=20241013T221345
[2024-10-13T18:13:45.757-0400] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-13T18:13:45.758-0400] {standard_task_runner.py:124} ERROR - Failed to execute job 204 for task load_task (Cannot resolve is_installed in UPDATE clause given columns new.station_id, new.capacity, new.eightd_has_key_dispenser, new.electric_bike_surcharge_waiver, new.external_id, new.has_kiosk, new.is_charging, new.lat, new.lon, new.name, new.rental_methods, new.short_name, new.eightd_station_services, new.eightd_has_available_keys, new.status_is_charging, new.status_is_installed, new.status_is_renting, new.status_is_returning, new.status_last_reported, new.status_num_bikes_available, new.num_bikes_disabled, new.num_docks_available, new.num_docks_disabled, new.num_ebikes_available, new.eightd_active_station_services, new.last_reported; 90923)
Traceback (most recent call last):
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/karenwang/airflow/dags/bixi_etl_pipeline.py", line 123, in load_data_to_delta
    delta_table.alias("existing") \
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/delta/tables.py", line 1036, in execute
    self._jbuilder.execute()
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: Cannot resolve is_installed in UPDATE clause given columns new.station_id, new.capacity, new.eightd_has_key_dispenser, new.electric_bike_surcharge_waiver, new.external_id, new.has_kiosk, new.is_charging, new.lat, new.lon, new.name, new.rental_methods, new.short_name, new.eightd_station_services, new.eightd_has_available_keys, new.status_is_charging, new.status_is_installed, new.status_is_renting, new.status_is_returning, new.status_last_reported, new.status_num_bikes_available, new.num_bikes_disabled, new.num_docks_available, new.num_docks_disabled, new.num_ebikes_available, new.eightd_active_station_services, new.last_reported
[2024-10-13T18:13:45.796-0400] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-13T18:13:45.812-0400] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-13T18:13:45.813-0400] {local_task_job_runner.py:245} INFO - ::endgroup::
