[2024-10-13T18:47:36.943-0400] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-13T18:47:36.957-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bixi_etl_pipeline.transform_task manual__2024-10-13T22:47:04.256111+00:00 [queued]>
[2024-10-13T18:47:36.964-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bixi_etl_pipeline.transform_task manual__2024-10-13T22:47:04.256111+00:00 [queued]>
[2024-10-13T18:47:36.964-0400] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-13T18:47:36.979-0400] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): transform_task> on 2024-10-13 22:47:04.256111+00:00
[2024-10-13T18:47:36.987-0400] {standard_task_runner.py:72} INFO - Started process 2455 to run task
[2024-10-13T18:47:36.995-0400] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-13T18:47:37.006-0400] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'bixi_etl_pipeline', 'transform_task', 'manual__2024-10-13T22:47:04.256111+00:00', '--job-id', '217', '--raw', '--subdir', 'DAGS_FOLDER/bixi_etl_pipeline.py', '--cfg-path', '/var/folders/bj/4z3t139j7xj2qng4wk4y16ym0000gn/T/tmpfiayvd7_']
[2024-10-13T18:47:37.007-0400] {standard_task_runner.py:105} INFO - Job 217: Subtask transform_task
[2024-10-13T18:47:37.071-0400] {task_command.py:467} INFO - Running <TaskInstance: bixi_etl_pipeline.transform_task manual__2024-10-13T22:47:04.256111+00:00 [running]> on host karendembp.home
[2024-10-13T18:47:37.360-0400] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bixi_etl_pipeline' AIRFLOW_CTX_TASK_ID='transform_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T22:47:04.256111+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-13T22:47:04.256111+00:00'
[2024-10-13T18:47:37.362-0400] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-13T18:47:37.362-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-13T18:47:37.363-0400] {logging_mixin.py:190} INFO - Current task name:transform_task state:running start_date:2024-10-13 22:47:36.957907+00:00
[2024-10-13T18:47:37.364-0400] {logging_mixin.py:190} INFO - Dag name:bixi_etl_pipeline and current dag run status:running
[2024-10-13T18:47:37.365-0400] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-13T18:47:42.298-0400] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/karenwang/airflow/dags/bixi_etl_pipeline.py", line 84, in transform_data
    convert_unix_time_udf = udf(convert_unix_time, TimestampType())
NameError: name 'udf' is not defined
[2024-10-13T18:47:42.306-0400] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-13T18:47:42.308-0400] {logging_mixin.py:190} INFO - Task start:2024-10-13 22:47:36.957907+00:00 end:2024-10-13 22:47:42.306361+00:00 duration:5.348454
[2024-10-13T18:47:42.309-0400] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform_task> dag:<DAG: bixi_etl_pipeline> dagrun:<DagRun bixi_etl_pipeline @ 2024-10-13 22:47:04.256111+00:00: manual__2024-10-13T22:47:04.256111+00:00, state:running, queued_at: 2024-10-13 22:47:04.288035+00:00. externally triggered: True>
[2024-10-13T18:47:42.310-0400] {logging_mixin.py:190} INFO - Failure caused by name 'udf' is not defined
[2024-10-13T18:47:42.312-0400] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=bixi_etl_pipeline, task_id=transform_task, run_id=manual__2024-10-13T22:47:04.256111+00:00, execution_date=20241013T224704, start_date=20241013T224736, end_date=20241013T224742
[2024-10-13T18:47:42.325-0400] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-13T18:47:42.326-0400] {standard_task_runner.py:124} ERROR - Failed to execute job 217 for task transform_task (name 'udf' is not defined; 2455)
Traceback (most recent call last):
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/karenwang/airflow/dags/bixi_etl_pipeline.py", line 84, in transform_data
    convert_unix_time_udf = udf(convert_unix_time, TimestampType())
NameError: name 'udf' is not defined
[2024-10-13T18:47:42.375-0400] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-13T18:47:42.399-0400] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-13T18:47:42.403-0400] {local_task_job_runner.py:245} INFO - ::endgroup::
